### PR TITLE
added dinner recipe

### PR DESCRIPTION
**Pull request by fioj14**
added scampi yummy
@bhl212 pls review

### CODE REVIEW

**Review by bhl212 — COMMENTED** [review]
LGTM @fioj14!

**Comment by isaacmcastro94** [comment]
Thanks for getting this in there! I'm going to approve this request!

**Review by isaacmcastro94 — APPROVED** [review]

**Review by bhl212 — APPROVED** [review]
Love scampi! LGTM! @fioj14 . will approve

**Comment by isaacmcastro94** [comment]
Figured out the issue!!! Just merged, so were good to keep updating!

**Pull request merged**
